<html>
<head>
  <meta charset="utf-8">
  <title>Formulaire</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<style>
  body{
    background-color: #F1F1F1FF;
  }
  ul{
    list-style: none;
  }
  .Basse{
    color:black;
  }
  .Normal{
    color: green;
  }
  .Haute{
    color: red;
  }
  .task-list li input:checked +label{
  text-decoration: line-through;
 } 
 .task-list label + p
{
  /* structure */
  display: none;
  margin-left: 1.5em; 
  margin-right: 1.5em; 
  padding: 1em;

  /* presentation */
  border: 1px solid #122430;
  border-radius: 4px;
  font-size: 0.875em;
  font-style: italic;
  text-align: justify;
}
.task-list label:hover + p
{
  display: block;
}

</style>
<body>
<h2 style="color: #00AA7FFF;text-align: center;">Bienvenue sur notre site</h2>
<nav class="navbar navbar-expand-lg navbar-light bg-light container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#"><img src="logo.png"></a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03 text-right">
   <h1 style="color: #FF5500FF; text-align: center; padding-right: 9em;padding-left:5em;" >Todo List 3W</h1>
   <pre>
    <?php $today = date("m/d/Y");echo $today; ?>
    </pre>
  </div>
</nav>
<br><br><br><br>
<hr>
<h1 style="color: #FF6A00FF">Gestionnaire de tâches </h1>

    <?php if(empty($tasks) == false): ?>
      <!-- Formulaire listant toutes les tâches existantes avec possibilité de suppression. -->
      <form class="standard-form" action="remove.php" method="POST">
        <ul class="task-list">
          <?php foreach($tasks as $index => $taskData): ?>
            <li>
              <input  id="task-<?= $index ?>" type="checkbox" name="indexes[]" value="<?= $index ?>">
              <label for="task-<?= $index ?>" class="<?= $taskData[3] ?> ">
                <?= $taskData[0] ?>
                                <?php if(date_create($taskData[2]) < $now): ?>
                                    <strong>- en retard</strong>
                                <?php endif ?>
              </label>
              <p class="<?= $taskData[3] ?> "><?= $taskData[1].'<br>'.$taskData[2].'<br>Périorité: '.$taskData[3]; ?></p>
            </li>
          <?php endforeach ?>
          <li>
            <input class="col-md-3 btn btn-danger" type="submit" value="Supprimer" title="Supprimer les tâches sélectionnées">
          </li>
        </ul>
      </form>
      <hr>
    <?php endif ?>
<h2 style="color: #FF6A00FF">Nouvelle tâche</h2>
<br>
<hr>
<form method="POST" action="add.php">
  <div class=" container">
  	<label class="col-md-4" for="titre"><b>Titre</b></label>
   <input class="col-md-6" style="width: 50%" type="text" name="titre" placeholder="Input"
   required >
   <label class="col-md-4" for="tache"><b>Tache</b></label>
   <input class="col-md-6" style="width: 50%;height: 200px" type="textarea" name="tache"placeholder="Texte"required >
   <br><br>
   <label class="col-md-4"  for="dat"><b>Date de fin</b></label>
 
   <select name="jour" >
        <?php 
        for ($i=1; $i <=31 ; $i++):
            ?>
            <option value = "<?php echo $i ?>" ><?php echo $i ?></option>  
        <?php endfor;?>
        </select>
        <select name="mois">
            <?php 
            $tab=array("janvier","fevrier","mars","Avril","Mais","Juin","juillet","Aout","septembre","octobre","novembre","decembre");
        for ($i=0; $i <=11 ; $i++):

            ?>
            <option value = "<?= $i+1 ?>"><?= $tab[$i] ?></option>  
        <?php endfor;?>
        </select>

        <select name="annee">
            <?php 
        for ($i=2019; $i <2031 ; $i++):
            ?>
            <option value = "<?php echo $i ?>"><?php echo $i ?></option>  
        <?php endfor;?>
        </select><br>
   <br><br>
   <label class="col-md-4"><b>Niveau de périorité</b></label>
   <label class="col-md-1"  for="Priorite"><b>Basse</b></label>
   <input value="Basse" type="radio" name="choix" >
<label class="col-md-1" for="Priorite"><b>Normal </b></label>
   <input value="Normal" type="radio" name="choix" >
<label class="col-md-1" for="Priorite"><b>Haute</b></label>
   <input value="Haute" type="radio" name="choix" >
<br>
<br><br>

<div class="row">
<div class="col-md-5"></div>
   <button  class="col-md-3 btn btn-success" type="submit
   "name="save" ><b>Enregistrer</b></button>
   </div>
   <br>
   <?php 

 ?>
 </div>
</form>
<hr>

</body>
</html>